apiVersion: apps/v1
kind: Deployment
metadata:
  name: bear
spec:
  selector:
    matchLabels:
      app: bear
  replicas: 1 
  template: 
    metadata:
      labels:
        app: bear
        canary: enabled
    spec:
      containers:
      - name: bear
        image: supergiantkir/animals:bear
        ports:
        - containerPort: 80
