kind: Service      # Create new service
apiVersion: v1     
metadata:
  name: canary-service # Name of the service
spec:
  type: LoadBalancer
  selector:
    canary: enabled
  ports:          # Map incoming port to target port
  - name: http    # Setting multiple ports listterns 
    port: 80
    targetPort: 80
