apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-spring
spec:
  selector:
    matchLabels:
      app: spring
  replicas: 2 
  template: 
    metadata:
      labels:
        app: spring
    spec:
      containers:
      - name: spring
        image: yanivomc/spring-music:latest
        ports:
        - containerPort: 8080
